engines:
    csslint:
        enabled: false
    eslint:
        enabled: true
            config:
                ignore_warnings: true
ratings:
   paths:
    - "dist/combo.full.js"
exclude_paths:
    - "dist/combo"
